### ISSUE TITLE
上传xls文件，插件没有反应

### ISSUE THREAD

**Issue by Ncrybo** [zjut-bio-party-undergraduate-branch/Excel-Compare-and-Import#18]
上传xls, xlsx文件 都没有反应，，怎么办呢。

**Comment by 497363983** [comment]
当前版本需要excel中每个sheet都满足这个要求：https://ct8hv7vfy1.feishu.cn/docx/EOALdRssWoxksuxy7gucmECQnEc#N1tqdTgOMojqkqxDNP6clhU3nPe

**Comment by 497363983** [comment]
@Ncrybo 目前最新版本已更新，会对错误格式进行提示，新功能可参考文档https://ct8hv7vfy1.feishu.cn/docx/EOALdRssWoxksuxy7gucmECQnEc
